spring:
  application:
    name: smart-backend
  datasource:
    url: jdbc:mysql://mysql:3306/smart_backend?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: redis
    port: 6379
    password: ${REDIS_PASSWORD}
    database: 0

server:
  port: 8080
  forward-headers-strategy: native

jwt:
  secret: ${JWT_SECRET}
  expire: ${JWT_EXPIRE:86400000}
  member:
    secret: ${JWT_MEMBER_SECRET}
    expire: ${JWT_MEMBER_EXPIRE:604800000}

upload:
  path: ${user.dir}/uploads/

logging:
  level:
    com.example.smartbackend: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

alipay:
  app-id: 9021000164663242
  private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCZ3ZlTCzghvAqMrFrN/XmVuaQG5iCyLokKj79vlwngXmywwTDYfVSrDKIirOhEdxqSYw26B5u/vE8wUkq95Us4sSl8H9wTBq7fwvBVsTzLiSl/Way/KO6DclH1Meo78WUBLGScrJ8qFYQkwq1/fVUQomZX1ZnR/s9BGkNPU6gJHP1J7rTVvcslxvWnDDv+lIlIkusP7a+yq3mR8e+KvKIHnqMdTnZBzihBXCQP9xHNPJNk0ewQPllRKuOmy9YEcNlavtDT+x8D/vqz1Y1UFpV0O0B/eW0yNXUYOKFBjlS+rvWKtu8NLiZkqmU8HWn+rHocaDYR13nUMoEnfK/X0sVpAgMBAAECggEAAMZW4U4rKDBUNUUg5+yg0hovM0GxZHRLiFwU8LDoAdM35OP0JQLsjDfyEQ6h1MZswdPx27/yDtMZ6vpfGfmvmUd7F/7pEsdz1fibUTMlRTkZlmSTNBs2qD7JHtzzev3KLmlU0F0mKAYXtj+ss/mjlgPbVBHlRmNsE73YHOwk6nbS5+bFjsvByhCga8bc4pzvdKSD/04Bl07ZboeAO1+EAeCd1+upCpj1TYgJU3MfVUsNITAgKfQakTbmAt5QzY2tYzNm8G/ALzWTvh63llwvrqzTGqf4B4pfEU19YEE2/9vXdPrFoQ/SnzjWZyFTeYvrybKdaPdGKM4E2U4sQYcXIQKBgQDKg09LFJoX37+cH3byVQKQDocLPaVuovA1kOGbwvNI+pj55qEEKzCWitQK1HlmKY0fEgILUvC1m9Vyzmw1n6JwJ9FZM3BtF+YqSzvTBzFcv4iRfLk+H7lgHR0VSISfSsZ/ue9STLm4wJ3BgFN/g+v+yFAp/PPEJK457RoFEmlxRQKBgQDCgQ39e9pTN74NMUD+C3RxBVEyMOwFFZiO9XrKka3mtac8MNs+sDc/GldWI97PAHpf99mwlMGZYGo2EYarWx/pSyOpZpm6fJKlM34HClsajxF/UQutICMsgag1SUIkVDmre0TQFKls1JDPM3c3YNhFUjrfabEwMbSk19jsKsRb1QKBgQCxpn0hvQHsXZDGEWgT73UfEE9xEfQU2QTlyKHRNTScWZFm7+ViNc0a0tBua7PPZjXxAqgebPTSK9EUNHcCl3Y08wkYOiKu4N89TOA/IDkyRqc0EXijQcspwIBp0kLdRghZta92v+3QX9BEFiGpY/3bdLe2Dbt93jukfxVrS5qKDQKBgQCoipXp4emklLfdzKFJwflLelUKjfPmz/jbYAHgCG5NbXkVoixJXP7yckvdu8V1UC+6exWqeqxr0G0YnwU39QVo7ZBgWSS6wPl9p2n8hc+96t05mqvof+GazltImUt0GXvDiVRujojlYih9M1aJqSSepQuYzogYf+nNsbAprUFrZQKBgCdsB93p2OV+epYCCi6k8CnEgP6E0U/5C7ODZ27P8yt2hm1UXulXFlR40dH4iEb/wJa+c/HFyU1fkVzLavkuFl83LWW9fzBpQMpvm4EXkggK+lMP95MgzWrMxSyR2lLyYPPSkJjO6cwuRv2eBHWD6WeIFKua5QIr/gi4C40cogHA
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgeR6eR3Z47fIc8lxoR7TlRE5OAQFKRlwavs3n0Bzfi+bkxcYSoj05I0nj3WrLUOThmpe7nVqwnuSJ5RDhv0QRoxstHZd9ZnpJjcgiwmHj5k7dFju+nXnKW8gx1MT/N8XUema9KG1MrrIC93uJyR0WbPAh1oxdv5YmPqN7XCZGsH/NLlE9PEmfeNlskS1Zv8re5y+tShkyU9ofiKqZeNP8TkaFxTR3edCHrb7wkwu0jIe5CKcFihze1/GYpYMCacZinA9yA8FMPsfRJH+49zQznqdmNSZv9ThKYdWvog+YTgkuOjGxKZaYlCftT75AshKbu8qa9cEAfMmJ7B6UJhAowIDAQAB
  gateway: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  notify-url: http://123.56.20.36/api/pay/notify
  return-url: http://123.56.20.36/order/list
